### ISSUE TITLE
Gantt charts need putting in the report

### ISSUE THREAD

**Issue by chewett** [soton-ecs-2014-gdp-12/reports#33]
@cbaines Could you look at putting these in the report somewhere, making a second one to show how the plan has changed, and add it "Agree deliverables with customer" for the 14-12-01?

Thanks

**Comment by chewett** [comment]
How is this going? Did this get adjusted by anyone?

**Comment by cbaines** [comment]
Sam and I made some adjustments, so they are different now. Some more might need doing?

**Comment by samuelbennett** [comment]
I dunno if maybe we should have more detail in out "Actual Gantt chart"?
