### ISSUE TITLE
Checks at the end

### ISSUE THREAD

**Issue by marialynch23** [soton-ecs-2014-gdp-12/reports#48]
As of [ddd450a](https://github.com/soton-ecs-2014-gdp-12/reports/commit/ddd450ab174018dc42c06f8f4f04e1f09cbe6d03)

- Referencing style consistent
- ~~All figures referred to in the text~~ 
- ~~All figures captioned~~ 
- ~~All tables referred to in the text~~ 
- ~~All tables captioned~~ 
- ~~All listings referred to in the text~~
- ~~All listings captioned~~ 
- Add relevant glossary entries 
- Ensure glossary used throughout
- ~~All content within the margins~~ 
- ~~Check spelling~~
- All sections introduced
- ~~Consistent voice~~
- No empty sections
- Requirements mentioned throughout
- Remove todo list

Word count: 16959
Pages: 174

**Comment by chewett** [comment]
All modules e.g. VideogularQuestions, etc need the to be the same case.

**Comment by samuelbennett** [comment]
Diagrams (punchcard and commits) need to be up to date
