### ISSUE TITLE
System architecture diagram needs explaining

### ISSUE THREAD

**Issue by marialynch23** [soton-ecs-2014-gdp-12/reports#50]
Bidirectional arrows need to be split and labelled correctly

**Comment by samuelbennett** [comment]
Diagram has been fixed in 65c22d. Still needs explaining

**Comment by cbaines** [comment]
I have added an initial description.

**Comment by samuelbennett** [comment]
Good start. 
We think it needs to be more detailed (3 or 4 times as long). Gonna reopen so it isn't forgotten

**Comment by HarryCutts** [comment]
I've added a lot of description in ff2879e, and a bit about why we made the decisions. There are a couple of TODOs for changes to the diagram in there.
