### ISSUE TITLE
Glossary counter/thing needs to be reset at each chapter

### ISSUE THREAD

**Issue by chewett** [soton-ecs-2014-gdp-12/reports#68]
Currently we use the glossary a lot and therefore a lot of acronyms are used in the first chapter and then we forget what they are used for.

Sam/Maria mentioned adding in something to the chapter preamble thing to reset this, to the full word is shown the first time used in every chapter. This seems very helpful. Doesnt seem to be a ticket so far :)

**Comment by samuelbennett** [comment]
Done in d182ee2.
