### ISSUE TITLE
We need screenshots of everything we made

### ISSUE THREAD

**Issue by marialynch23** [soton-ecs-2014-gdp-12/reports#74]
(pull first Maria made some accessibility changes)

**Comment by marialynch23** [comment]
@chewett suggested images of every type of question we have

**Comment by cbaines** [comment]
I have added screenshots of things to the report.

**Comment by chewett** [comment]
Awesome work chris, im just going to re-open this, as this screenshot has some quirkyiness. It shouldnt appear like that (pick another browser someone?)

https://github.com/soton-ecs-2014-gdp-12/reports/blob/78755f958bb09d727c735cfd2b11ee6ab3d425f9/report/screenshots/videogular-questions-example-question-range.png

**Comment by cbaines** [comment]
It appears to happen in both Firefox and Chromium, but it is dependant on the window size.

**Comment by cbaines** [comment]
I have pushed the updated screenshot in 62382505324d00cee485d9ce5b0da35d34de4e2e
